In [2]:
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [3]:
b=a.shape
print("shape",b)

shape (3, 3)


In [4]:
c=a.ndim
print("no of dimension",c)

no of dimension 2


In [8]:
z=np.zeros((2,2))
print("zeros\n",z)
o=np.ones((2,2))
print("ones\n",o)

zeros
 [[0. 0.]
 [0. 0.]]
ones
 [[1. 1.]
 [1. 1.]]


In [10]:
a=np.array([[1,2,3,4],[2,3,4,5],[3,4,5,6],[4,5,6,7]])
b=a.reshape(4,2,2)
print("reshape\n",b)
c=a.flatten()
print("flatten\n",c)

reshape
 [[[1 2]
  [3 4]]

 [[2 3]
  [4 5]]

 [[3 4]
  [5 6]]

 [[4 5]
  [6 7]]]
flatten
 [1 2 3 4 2 3 4 5 3 4 5 6 4 5 6 7]


In [12]:
#vertically
v=np.vstack(a)
print("vertically\n",v)

vertically
 [[1 2 3 4]
 [2 3 4 5]
 [3 4 5 6]
 [4 5 6 7]]


In [14]:
h=np.hstack(a)
print("horizantally\n",h)

horizantally
 [1 2 3 4 2 3 4 5 3 4 5 6 4 5 6 7]


In [20]:
print(a)
temp=a[[0,1,2,3],[1,1,1,1]]
print("indexing",temp)

[[1 2 3 4]
 [2 3 4 5]
 [3 4 5 6]
 [4 5 6 7]]
indexing [2 3 4 5]


In [21]:
i=a[:4,::2]
print(i)

[[1 3]
 [2 4]
 [3 5]
 [4 6]]


In [16]:
import numpy as np
a=np.array([[0,2,-5,4],[1,-3,4,-7]])
min=a.min()
print("min",min)
max=a.max()
print("max",max)

min -7
max 4


In [15]:
import numpy as np
a=np.array([1,2,3,4,5])
mean=a.mean()
print("mean",mean)
median=np.median(a)
print("median",median)
std=np.std(a)
print("Standard deviation",std)

mean 3.0
median 3.0
Standard deviation 1.4142135623730951
